set(MOD_VERSION "1.0.0")
set(MOD_ID "AdaptiveAudioLatency")
set(COMPILE_ID "AdaptiveAudioLatency")

set(EXTERN_DIR_NAME "extern")
set(SHARED_DIR_NAME "shared")

if (NOT DEFINED CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE "RelWithDebInfo")
endif()

if (NOT DEFINED CMAKE_ANDROID_NDK)
	if(EXISTS $ENV{ANDROID_NDK_HOME})
		set(CMAKE_ANDROID_NDK $ENV{ANDROID_NDK_HOME})
	elseif(EXISTS $ENV{ANDROID_NDK_ROOT})
		set(CMAKE_ANDROID_NDK $ENV{ANDROID_NDK_ROOT})
	elseif(EXISTS "/opt/android-ndk")
		set(CMAKE_ANDROID_NDK "/opt/android-ndk")
	endif()
endif()
message(STATUS "Using NDK: ${CMAKE_ANDROID_NDK}")
string(REPLACE "\\" "/" CMAKE_ANDROID_NDK ${CMAKE_ANDROID_NDK})

set(ANDROID_PLATFORM 24)
set(ANDROID_ABI arm64-v8a)
set(ANDROID_STL c++_static)
set(ANDROID_USE_LEGACY_TOOLCHAIN_FILE OFF)

set(CMAKE_TOOLCHAIN_FILE ${CMAKE_ANDROID_NDK}/build/cmake/android.toolchain.cmake)
set(EXTERN_DIR ${CMAKE_CURRENT_SOURCE_DIR}/${EXTERN_DIR_NAME})
set(SHARED_DIR ${CMAKE_CURRENT_SOURCE_DIR}/${SHARED_DIR_NAME})

MACRO(RECURSE_FILES return_list filter)
	FILE(GLOB_RECURSE new_list ${filter})
	SET(file_list "")
	FOREACH(file_path ${new_list})
		SET(file_list ${file_list} ${file_path})
	ENDFOREACH()
	LIST(REMOVE_DUPLICATES file_list)
	SET(${return_list} ${file_list})
ENDMACRO()
